### PR TITLE
JBIDE-19080: Rename org.jboss.tools.hibernate.spi into org.jboss.tools.h...

### PR DESCRIPTION
**Pull request by koentsje**
...ibernate.runtime.spi

### CODE REVIEW

**Comment by fbricon** [comment]
That's an API breakage that requires plugin major upversionning

**Comment by koentsje** [comment]
Correct. I have upversioned the plugin versions to 5.0.0.

**Comment by fbricon** [comment]
you also need to update the minimum version required in downstream manifests

**Comment by koentsje** [comment]
Right... done

**Comment by maxandersen** [comment]
will this affect seam or others ?

**Comment by koentsje** [comment]
Yes, but that's why I opened this PR in the first place ;-)

**Comment by alexeykazakov** [comment]
Looks good. I squashed the commits and pushed to the master.

**Pull request closed without merging**
