### PR TITLE
JBIDE-19646 Move org.jboss.tools.jsf.vpe.seam into the Seam module

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by maxandersen** [comment]
Two comments: 

1) I thought we had it in jsf so Seam it self would not drag in VPE - is that not relevant anymore ?
2) Since this is just a legacy component/feature why not just move it over as is - no package/bundle renames ?

**Comment by alexeykazakov** [comment]
1) Seam didn't depend on VPE plugins. But Seam feature requires JSF (and depends on some JSF plugins) and JSF depends on VPE. So Seam feature drags in VPE anyway.
2) Just to make seam code more clean/consistent. Not a big deal imho. Denis was +1 to rename the plugins. I was +-0. So, are you -1?

**Comment by maxandersen** [comment]
1) okey then not a biggie.
2) i'm -0 ;) if its already done its done - just always worried if some p2 update path we break with this or some user preference values that gets changed.

**Comment by alexeykazakov** [comment]
Rebased and pushed to master.

**Pull request closed without merging**
