### PR TITLE
[JBDE-26030] - Remove XULRunner related code

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@jeffmaury Build failed, I got the same situation locally where o.j.t.cdi.seam.core.test failed due to timeout `[ERROR] Timeout 2400 s exceeded. Process was killed.`
Eclipse just hangs in that place. Trying to find out more.

**Comment by jeffmaury** [comment]
@odockal I turns out that on master we don't run the tests for cdi and seam so I suspect the PR check is wrongly configured. I'm checking on my laptop with an increased timeout

**Comment by jeffmaury** [comment]
Updated the PR job with a surefire.timeout=3600

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
Increasing the timeout is not the solution but I ran tests against batch and jsf (as master does) and it was successful. So I think we're good to go.

**Comment by odockal** [comment]
@jeffmaury do you think it will work? Anyway, I encounter another error: you have removed templates folder from o.j.t.seam.vpe and it is included in build.properties, I will to remove all such leftovers and add commit to your PR, so we may at least have it build.

**Comment by nickboldt** [comment]
Merged because it's code freeze day and aggregates for jbt core and core tests are broken.

**Pull request merged**
