### PR TITLE
jbide-22994: Remove old Help->Report Problem dialog

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@bdshadow please work with QE guys to fix the problem with JavaEE integration tests checks for PRs.

**Comment by rawagner** [comment]
Deltaspike PR tests are broken, PR is already created https://github.com/jbosstools/jbosstools-integration-tests/pull/1617

I dont have any objections from CDI/Deltaspike integration tests side, so +1 to this PR

@mlabuda can you check jsf tests ?

**Comment by mlabuda** [comment]
JSF tests are unstable, not runnable on jenkins. The tests have to be rewritten so not blocking from JSF side.

**Comment by alexeykazakov** [comment]
OK. Thanks. Merging because this is a blocker and should be fixed ASAP. We need to keep working on fixing/improving integration tests though.

**Pull request merged**
