### PR TITLE
JBIDE-23861 Enable CDI support when beans xml is created and cdi lib …

### PR DESCRIPTION
**Pull request by rawagner**
…is in build path

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
@jeffmaury can you please take a look ?

**Comment by jeffmaury** [comment]
I updated the PR title to reflect the correct JIRA but can you update the commit message as well

**Comment by rawagner** [comment]
whoops, sorry. Commit msg updated

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
batch-integration-tests failure is not related to changes in this PR

**Pull request merged**
