### PR TITLE
JBIDE-27141: fix build for 4.15.0.AM1

### PR DESCRIPTION
**Pull request by sbouchet**
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=558800 for upstream
cause.

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

### CODE REVIEW

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Pull request merged**
