### PR TITLE
JBIDE-28994 : removed seam and jsf from release

### PR DESCRIPTION
**Pull request by sbouchet**

### CODE REVIEW

**Comment by sbouchet** [comment]
> I don't fully understand why "org.jboss.tools" was removed ?

groupId already defined in parent, it is redundant.

**Review by olkornii — APPROVED** [review]
LGTM

**Comment by olkornii** [comment]
@sbouchet 
But GA are still failed, is it ok?

**Comment by sbouchet** [comment]
TP is under update, not fully available for builds. will keep open until build passes

**Pull request merged**
