### PR TITLE
JBIDE-26461 - Changed internal API - package of StubUtility class 

### PR DESCRIPTION
**Pull request by odockal**
StubUtility moved to org.eclipse.jdt.internal.core.manipulation, see https://github.com/eclipse/eclipse.jdt.ui/commit/bc3bc858da1855f31cee9566912859faac05819e.

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@jeffmaury @nickboldt @adietish whoever will be looking at this, I have not tried it locally, yet.

**Comment by nickboldt** [comment]
*touches nose* Not it!

**Comment by odockal** [comment]
@nickboldt Had to bump up every component, and also change import in batch which used problematic class as well, but local build went alright. Let's see jenkins pr check.

**Comment by odockal** [comment]
Build is yellow - there is one test failure due to same thing, but originated in jbt-base/common, so I did another PR: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-javaee-Pull-Request/112/. Though, this one can be compiled at least.

**Comment by odockal** [comment]
testPR

**Pull request merged**
